name: 'real world tests'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: 'macos-latest'
            args: '--verbose --target universal-apple-darwin'
          - platform: 'ubuntu-latest'
            args: '--verbose'
          - platform: 'windows-latest'
            args: '--verbose'

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4

      # node
      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # example-with-tauri tests the auto installation of the tauri cli
      - name: install example dependencies
        run: pnpm install
        working-directory: ./__fixtures__/example

      # rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            ./__fixtures__/example/src-tauri -> ../../target
            ./__fixtures__/example-with-tauri/src-tauri -> ../../target

      # system
      - name: install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

      - name: Preconfigured Tauri Project
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Updater signature is exposed here to make sure it works in PR's
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5YTBGV3JiTy9lRDZVd3NkL0RoQ1htZmExNDd3RmJaNmRMT1ZGVjczWTBKZ0FBQkFBQUFBQUFBQUFBQUlBQUFBQWdMekUzVkE4K0tWQ1hjeGt1Vkx2QnRUR3pzQjVuV0ZpM2czWXNkRm9hVUxrVnB6TUN3K1NheHJMREhQbUVWVFZRK3NIL1VsMDBHNW5ET1EzQno0UStSb21nRW4vZlpTaXIwZFh5ZmRlL1lSN0dKcHdyOUVPclVvdzFhVkxDVnZrbHM2T1o4Tk1NWEU9Cg==
        with:
          projectPath: ./__fixtures__/example-with-tauri
          includeDebug: true
          includeRelease: false
          tagName: ${{ github.event.pull_request.head.repo.full_name == github.repository && 'example-with-tauri-v__VERSION__' || '' }}
          releaseName: 'Release example with preconfigured Tauri app v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          args: ${{ matrix.settings.args }}

      - name: Frontend-only Project
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Updater signature is exposed here to make sure it works in PR's
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5YTBGV3JiTy9lRDZVd3NkL0RoQ1htZmExNDd3RmJaNmRMT1ZGVjczWTBKZ0FBQkFBQUFBQUFBQUFBQUlBQUFBQWdMekUzVkE4K0tWQ1hjeGt1Vkx2QnRUR3pzQjVuV0ZpM2czWXNkRm9hVUxrVnB6TUN3K1NheHJMREhQbUVWVFZRK3NIL1VsMDBHNW5ET1EzQno0UStSb21nRW4vZlpTaXIwZFh5ZmRlL1lSN0dKcHdyOUVPclVvdzFhVkxDVnZrbHM2T1o4Tk1NWEU9Cg==
        with:
          projectPath: ./__fixtures__/example
          distPath: ../dist # relative to tauri.conf.json
          iconPath: ./icon.png # relative to projectPath
          bundleIdentifier: com.tauri.actiontest
          appName: example
          appVersion: ../package.json # relative to tauri.conf.json
          includeDebug: true
          includeRelease: false
          tagName: ${{ github.event.pull_request.head.repo.full_name == github.repository && 'example-v__VERSION__' || '' }}
          releaseName: 'Release example app v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          args: ${{ matrix.settings.args }}